require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.1
  NewCops: enable
  Exclude:
    - '**/db/migrate/*'
    - 'db/schema.rb'
    - '**/Gemfile.lock'
    - '**/Rakefile'
    - '**/rails'
    - '**/vendor/**/*'
    - '**/spec_helper.rb'
    - '**/test/**/*'
    - 'bin/*'

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - '**/app/presenters/api/**/*'
    - '**/app/controllers/api/**/*'
    - '**/app/services/**/**/**/*'

Lint/EmptyClass:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Layout/LineLength:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Metrics/MethodLength:
  Exclude:
    - '**/lib/**/*'
    - '**/app/models/user.rb'
    - '**/app/services/px/media_aggregate/list_service.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - '**/app/services/px/medium/patch_service.rb'

Style/GlobalVars:
  AllowedVariables:
    - $redis

Style/HashSyntax:
  EnforcedShorthandSyntax: never

RSpec/MessageSpies:
  EnforcedStyle: receive

Layout/TrailingEmptyLines:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Performance/MapCompact:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/RescueStandardError: 
  Enabled: false

Metrics/MethodLength:
  Enabled: false