name: CI/CD Pipeline

env:
  CONFIG_REPO_NAME: px-file-upload-service-repo-test
  AWS_REGION: us-west-1  # Set the AWS region as an environment variable

on:
  push:
    branches:
      - 'main'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building and testing the castingapp !!!! ..."

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
          skip-logout: false
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: WebApplication1/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com/ca-upload-service-dev:${{ github.sha }}

  promote-to-dev-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Promote to Dev Environment
        run: |
          echo "Promoting into dev environment!"
          git config --global user.email demy@castingapp.com
          git config --global user.name demy
          echo "Cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          echo "Checkout main branch"
          git checkout main
          echo "Updating image tag in values file"
          sed -i "s,tag:.*,tag: ${GITHUB_SHA}," helm/castingwebapp/values.yaml
          git add . && git commit -m "Update image tag" || echo "No changes to commit"
          git push
