name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  update-and-push-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image tag in values.yaml
        run: |
          cd $CONFIG_REPO_NAME
          echo "Before:"
          cat helm/castingwebapp/values.yaml
          sed -i "s,tag:.*,tag: ${{ github.sha }}," helm/castingwebapp/values.yaml
          echo "After:"
          cat helm/castingwebapp/values.yaml
          git add helm/castingwebapp/values.yaml
          git status
          git commit -m "update image tag"
          git push
        env:
          CONFIG_REPO_NAME: px-file-upload-service-repo-test

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "Building and testing the app ..."

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: WebApplication1/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com/ca-upload-service-dev:${{ github.sha }}

  promote-to-dev-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Set up Git
        run: |
          git config --global user.email ci-bot@argocd.com
          git config --global user.name ci-bot
      - name: Clone config repo
        run: |
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          git checkout main
      - name: Update image tag in values.yaml
        run: |
          cd $CONFIG_REPO_NAME
          sed -i "s,tag:.*,tag: ${{ github.sha }}," helm/castingwebapp/values.yaml
          git add helm/castingwebapp/values.yaml
          git commit -m "update image tag"
          git push
