name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the castingapp ..."

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com/ca-upload-service-dev:${{ github.event.pull_request.head.sha }}

  update-image-tag-in-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          git config --global user.email "demy@castingapp.com"
          git config --global user.name "demy-ci-bot"
          echo "cloning app repo"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/px-file-upload-service-repo-test.git
          cd uploadservicedevtest
          echo "checkout source branch"
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "updating image tag in values file"
          sed -i "s,tag:.*,tag:\ ${{ github.event.pull_request.head.sha }}," helm/castingwebapp/values.yaml
          git add . && git commit -m "update image tag [skip ci]"
          git push

  add_labels:
    runs-on: ubuntu-latest
    needs: update-image-tag-in-helm
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            preview
